name: Pull Request - Build
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # See here for caching with `yarn` https://github.com/actions/cache/blob/main/examples.md#node---yarn or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
          path: |
            ~/.pnpm
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-
      - name: use pnpm with node
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm it
      - name: Generate build
        run: pnpm build
