name: Pull Request - Build
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - if: ${{ steps.cache-node.outputs.cache-hit != 'true' }}
        run: pnpm install
      - name: Generate build
        run: pnpm build
      - name: pnpm test
        run: pnpm test
